### ISSUE TITLE
Preference Packs

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/Addons#16]
### FreeCAD master

**Note:** checkboxed selections indicate they've been made in to a [Preference pack](https://wiki.freecad.org/Preference_Packs).  
*Realthunder's Link branch doesn't support preference packs (at this time)*
* [Original themes](https://github.com/pgilfernandez/FreeCAD_stylesheets) by @pgilfernandez (bundled in to master)
* [x] [BasicMech](https://github.com/macdroid53/BasicMech) by @macdroid53 Mechanical Design dark theme (WIP)
* [ ] [Blender theme](https://github.com/pgilfernandez/FreeCAD_Blender-stylesheet) by @pgilfernandez
* [x] [ProDark](https://github.com/turn211/ProDark-FreeCAD-theme) by @turn211 (Bundled in to master) (in Addon repo since 4d803504fa9181063f104baa8c50139d86e15e7f)
* [x] [Behave dark theme](https://github.com/Chrismettal/FreeCAD-Behave-Dark-Preference-Pack) by @Chrismettal (master) (In Addon repo since https://github.com/FreeCAD/FreeCAD-addons/commit/0d23295401db40d413abf45818e6800c287868e0)
* [ ] [freecad-stylesheets](https://github.com/MathiasStadler/freecad-Stylesheets) by @MathiasStadler 
* [ ] [Plane stylesheet](https://github.com/wfpaisa/Plane-freecad) by @wfpaisa
* [x] [Dracula dark theme](https://github.com/dracula/freecad) by @dracula (#228)
* [ ] [Prof-CAD Dark/Light Themes](https://github.com/OBKF/Prof-CAD) by @OBKF
* [x] [Extreme ProDark](https://github.com/MisterMakerNL/ExtremeProDark) by @MisterMakerNL (#229)  
* [ ] [ExtremeProLight](https://github.com/MisterMakerNL/ExtremeProLight) by @MisterMakerNL
* [ ] [GdsLightBlue](https://github.com/glassondesignstudio/GdsLightBlue/) by @glassondesignstudio
--------

### Link/LinkStage3/LinkDaily by @realthunder
* [OficineRobotica's Preference Presets](https://github.com/oficinerobotica/FreeCAD-Preferences-Presets) by @oficinerobotica's (Link/LS3/Daily)  
* [VertUI](https://github.com/StudioPetrikas/FreeCADLink_VertUI) by @StudioPetrikas (LinkDaily)
* [MidnightUI](https://petrikas.gumroad.com/l/midnight) by @StudioPetrikas (LinkDaily)
* [CadWin](https://github.com/rmTizi/CadWin) by @rmTizi (Link)
* [FreeCAD-Mechanical](https://snapcraft.io/freecad-mechanical) by @riqueenz
* [ ] [Extreme ProDark](https://github.com/MisterMakerNL/ExtremeProDark) by @MisterMakerNL (#226)

**Comment by chennes** [comment]
[GdsLightBlue](https://github.com/glassondesignstudio/GdsLightBlue) has been archived and should be removed from the list. 

Several of the others were created 6-7 years ago and are unlikely to still be active. I propose we simply close this issue in its current state, there's unlikely to be any further actions any of us can or should take.

**Comment by macdroid53** [comment]
Basic Mech can certainly be removed. It never left the example state.
